postgres:
  restart: always
  image: postgres:latest
  ports:
    - "5432:5432"
  env_file: .env
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: ''

redis:
  image: redis:latest
  ports:
    - "6379"

socketserver:
  build: socketserver
  restart: always
  ports:
    - "8080"
  links:
    - redis
  environment:
    PORT: 8080

web:
  build: ./web/
  restart: always
  working_dir: /usr/src/app
  ports:
    - "8000:8000"
  volumes:
    - web:/usr/src/app
  links:
    - postgres
    - redis
  command: python manage.py runserver 0.0.0.0:8000
  env_file: .env
  environment:
    DEBUG: 1
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: ''

celery:
  build: ./web/
  restart: always
  working_dir: /usr/src/app
  volumes:
    - web:/usr/src/app
  links:
    - postgres:postgres
    - redis:redis
  command: su -m celery_user -c "celery -A pokeradio  worker --loglevel=info"
  env_file: .env
  environment:
    DEBUG: 1
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: ''

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes_from:
    - web
  links:
    - web
    - socketserver
