dbdata:
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: true
 
db:
  image: aidanlister/postgres-hstore
  volumes_from:
    - dbdata
  ports:
    - "5432"

redisdata:
  image: redis:latest
  volumes:
    - /var/lib/redis
  command: true
 
redis:
  image: redis:latest
  volumes_from:
    - redisdata
  ports:
    - "6379"

socket:
  build: socketserver
  ports:
    - "8080:8080"
  links:
    - redis
  environment:
    - REDISCLOUD_URL=redis://redis:6379/0
    - PORT=8080

web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/usr/src/app/
  ports:
    - "8000:8000"
  links:
    - db
    - redis
  environment:
    - INSTANCE_TYPE=web
    - DEBUG=1
    - DJANGO_SETTINGS_MODULE=pokeradio.config.settings
    - DATABASE_URL=postgres://postgres@db/postgres
    - REDISCLOUD_URL=redis://redis:6379/0
