postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - postgresdata
  ports:
    - "5432:5432"

postgresdata:
  restart: no
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: true

redisdata:
  image: redis:latest
  volumes:
    - /var/lib/redis
  command: true

redis:
  image: redis:latest
  volumes_from:
    - redisdata
  ports:
    - "6379"

socketserver:
  build: socketserver
  restart: always
  ports:
    - "8080"
  links:
    - redis
  environment:
    - PORT=8080

web:
  build: ./web/
  restart: always
  working_dir: /usr/src/app
  ports:
    - "8000:8000"
  links:
    - postgres:postgres
    - redis:redis
  command: /usr/local/bin/gunicorn pokeradio.wsgi:application -w 2 -b :8000
  env_file: .env
  evironment:
      DEBUG: 0


nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes_from:
    - web
  links:
    - web:web
    - socketserver:socketserver
