db:
  image: mysql
  environment:
    - MYSQL_DATABASE=prad
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_USER=prad
    - MYSQL_PASSWORD=prad

redis:
  image: redis:latest
  ports:
    - "6379"

socketserver:
  build: socketserver
  restart: always
  ports:
    - "8080"
  links:
    - redis
  environment:
    PORT: 8080

web:
  build: ./web/
  restart: always
  working_dir: /usr/src/app
  ports:
    - "8000:8000"
  volumes:
    - "web:/usr/src/app"
  links:
    - db
    - redis
  command: python manage.py runserver 0.0.0.0:8000
  env_file: .env
  environment:
    - DEBUG=1
    - MYSQL_DATABASE=prad
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_USER=prad
    - MYSQL_PASSWORD=prad

celery:
  build: ./web/
  restart: always
  working_dir: /usr/src/app
  volumes:
    - "web:/usr/src/app"
  links:
    - db
    - redis
  command: su -m celery_user -c "celery -A pokeradio  worker --loglevel=info"
  env_file: .env
  environment:
    - DEBUG=1
    - MYSQL_DATABASE=prad
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_USER=prad
    - MYSQL_PASSWORD=prad

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes_from:
    - web
  links:
    - web
    - socketserver
